package com.erkindilekci.gamebook.presentation.mainlistscreen

import com.erkindilekci.gamebook.domain.model.Game

data class MainListState(
    val gameList: List<Game> = emptyList(),
    val pcGames: List<Game> = emptyList(),
    val webGames: List<Game> = emptyList(),

    var shooterGames: List<Game> = emptyList(),
    var mmoarpgGames: List<Game> = emptyList(),
    var arpgGames: List<Game> = emptyList(),
    var strategyGames: List<Game> = emptyList(),
    var mmorpgGames: List<Game> = emptyList(),
    var fightingGames: List<Game> = emptyList(),
    var actionArpgGames: List<Game> = emptyList(),
    var battleRoyaleGames: List<Game> = emptyList(),
    var mobaGames: List<Game> = emptyList(),
    var racingGames: List<Game> = emptyList(),
    var cardGameGames: List<Game> = emptyList(),
    var sportsGames: List<Game> = emptyList(),
    var mmoGames: List<Game> = emptyList(),
    var socialGames: List<Game> = emptyList(),
    var fantasyGames: List<Game> = emptyList(),

    var pcshooterGames: List<Game> = emptyList(),
    var pcmmoarpgGames: List<Game> = emptyList(),
    var pcarpgGames: List<Game> = emptyList(),
    var pcstrategyGames: List<Game> = emptyList(),
    var pcmmorpgGames: List<Game> = emptyList(),
    var pcfightingGames: List<Game> = emptyList(),
    var pcactionArpgGames: List<Game> = emptyList(),
    var pcbattleRoyaleGames: List<Game> = emptyList(),
    var pcmobaGames: List<Game> = emptyList(),
    var pcracingGames: List<Game> = emptyList(),
    var pccardGameGames: List<Game> = emptyList(),
    var pcsportsGames: List<Game> = emptyList(),
    var pcmmoGames: List<Game> = emptyList(),
    var pcsocialGames: List<Game> = emptyList(),
    var pcfantasyGames: List<Game> = emptyList(),

    var webshooterGames: List<Game> = emptyList(),
    var webmmoarpgGames: List<Game> = emptyList(),
    var webarpgGames: List<Game> = emptyList(),
    var webstrategyGames: List<Game> = emptyList(),
    var webmmorpgGames: List<Game> = emptyList(),
    var webfightingGames: List<Game> = emptyList(),
    var webactionArpgGames: List<Game> = emptyList(),
    var webbattleRoyaleGames: List<Game> = emptyList(),
    var webmobaGames: List<Game> = emptyList(),
    var webracingGames: List<Game> = emptyList(),
    var webcardGameGames: List<Game> = emptyList(),
    var websportsGames: List<Game> = emptyList(),
    var webmmoGames: List<Game> = emptyList(),
    var websocialGames: List<Game> = emptyList(),
    var webfantasyGames: List<Game> = emptyList(),
)